version: "3.9"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]

  backend:
    build:
      context: ./backend      # important: points to backend/
    command: ["./docker/entrypoint.sh"]
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  celery:
    build:
      context: ./backend
    command: ["celery", "-A", "config", "worker", "-l", "info"]
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis

volumes:
  pgdata:
